-- 코드를 입력하세요
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2)
FROM REST_INFO
JOIN REST_REVIEW USING(REST_ID)
GROUP BY REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
HAVING ADDRESS LIKE '서울%'
ORDER BY 6 DESC;